<?php

namespace Ffhs\FilamentPackageFfhsCustomForms\Filament\Resources\GeneralFieldsResource\Pages;

use Ffhs\FilamentPackageFfhsCustomForms\Filament\Resources\GeneralFieldResource;
use Filament\Actions\DeleteAction;
use Filament\Actions\LocaleSwitcher;
use Filament\Resources\Pages\EditRecord;
use Filament\Resources\Pages\EditRecord\Concerns\Translatable;

class EditGeneralField extends EditRecord
{
    use Translatable;

    protected static string $resource = GeneralFieldResource::class;

    public function mount(int|string $record): void
    {
        parent::mount($record); // TODO: Change the autogenerated stub
        $recordModel = $this->getRecord();
    }

    protected function mutateFormDataBeforeSave(array $data): array
    {
        if (!array_key_exists('extra_option_names', $data)) {
            return parent::mutateFormDataBeforeSave($data);
        }

        $names = $data['extra_option_names'];
        $overwriteOptions = $data['overwrite_options'];
        $allowedOverwriteOptions = [];

        foreach ($names as $name) {
            $allowedOverwriteOptions[$name] = $overwriteOptions[$name] ?? null;
        }

        unset($data['extra_option_names']);
        $data['overwrite_options'] = $allowedOverwriteOptions;

        return parent::mutateFormDataBeforeSave($data);
    }

    protected function getHeaderActions(): array
    {
        return [
            LocaleSwitcher::make(),
            DeleteAction::make(),
        ];
    }
}
