<?php

namespace Ffhs\FilamentPackageFfhsCustomForms\Filament\Resources\CustomFormAnswerResource\Pages;

use Ffhs\FilamentPackageFfhsCustomForms\Filament\Resources\CustomFormAnswerResource\CustomFormAnswerResource;
use Ffhs\FilamentPackageFfhsCustomForms\Models\CustomFormAnswer;
use Ffhs\FilamentPackageFfhsCustomForms\Traits\CanLoadFormAnswer;
use Ffhs\FilamentPackageFfhsCustomForms\Traits\CanSaveFormAnswer;
use Filament\Actions\DeleteAction;
use Filament\Actions\ViewAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Contracts\Support\Htmlable;
use Illuminate\Database\Eloquent\Model;

class EditCustomFormAnswer extends EditRecord
{
    use CanLoadFormAnswer;
    use CanSaveFormAnswer;

    protected static string $resource = CustomFormAnswerResource::class;

    public function getTitle(): string|Htmlable
    {
        $attributes = $this
            ->getRecord()
            ->attributesToArray();

        return trans(CustomFormAnswer::__('pages.edit.title'), $attributes);
    }

    public function mount(int|string $record): void
    {
        parent::mount($record); // TODO: Change the autogenerated stub
    }

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make(),
            ViewAction::make()
        ];
    }

    protected function mutateFormDataBeforeFill(array $data): array
    {
        $data = parent::mutateFormDataBeforeFill($data);

        /**@var CustomFormAnswer $customFormAnswer */
        $customFormAnswer = $this->form->getRecord();

        if (!$customFormAnswer->customFieldAnswers->isEmpty()) {
            return $data;
        }

        //Load data's from fields
        return ['form_answer' => array_merge($data, $this->loadCustomAnswerData($customFormAnswer))];
    }

    protected function handleRecordUpdate(Model $record, array $data): Model
    {
        /**@var CustomFormAnswer $customFormAnswer */
        $customFormAnswer = $this
            ->form
            ->getRecord();

        $this->saveFormAnswer($customFormAnswer, $this->form, 'data.form_answer');

        return $customFormAnswer->refresh();
    }
}
