<?php

namespace Ffhs\FilamentPackageFfhsCustomForms\Filament\Component\RuleEditor;

use Filament\Actions\Action;
use Filament\Support\Colors\Color;

class RuleRemoveAction extends Action
{
    public static function make(?string $name = 'remove'): static
    {
        return parent::make($name); // TODO: Change the autogenerated stub
    }

    protected function setUp(): void
    {
        parent::setUp();
        $this->icon('heroicon-c-trash')
            ->color(Color::Red)
            ->iconButton()
            ->action(function ($get, $set, $component) {
                $path = $component->getStatePath();
                $parts = explode('.', $path);
                $value = end($parts);
                $state = $get('../');
                unset($state[$value]);
                $set('../', $state);
            });
    }


}
