<?php

namespace Ffhs\FilamentPackageFfhsCustomForms\Resources\TemplateResource\Pages;

use Ffhs\FilamentPackageFfhsCustomForms\Resources\CustomFormResource\Pages\CreateCustomForm;
use Ffhs\FilamentPackageFfhsCustomForms\Resources\TemplateResource;

class CreateTemplate extends CreateCustomForm
{
    protected static string $resource = TemplateResource::class;

    protected function mutateFormDataBeforeCreate(array $data): array {
        $data["is_template"] = true;
        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }


}
