<?php

namespace Ffhs\FilamentPackageFfhsCustomForms\Resources\GeneralFieldsResource\Pages;

use Ffhs\FilamentPackageFfhsCustomForms\Resources\GeneralFieldResource;
use Filament\Actions;
use Filament\Resources\Pages\EditRecord;

class EditGeneralField extends EditRecord
{
    use EditRecord\Concerns\Translatable;

    protected static string $resource = GeneralFieldResource::class;

    public function mount(int|string $record): void
    {
        parent::mount($record); // TODO: Change the autogenerated stub
        $recordModel = $this->getRecord();
    }


    protected function mutateFormDataBeforeSave(array $data): array
    {
        //dd($data, $data['extra_option_names']);
        if(!array_key_exists('extra_option_names', $data)){
            return parent::mutateFormDataBeforeSave($data);
        }
        $names = $data['extra_option_names'];

        $overwriteOptions = $data['overwrite_options'];
        $allowedOverwriteOptions = [];
        foreach ($names as $name) $allowedOverwriteOptions[$name] = $overwriteOptions[$name] ?? null;

        unset($data['extra_option_names']);
        $data['overwrite_options'] = $allowedOverwriteOptions;

        return parent::mutateFormDataBeforeSave($data);
    }


    protected function getHeaderActions(): array
    {
        return [
            Actions\LocaleSwitcher::make(),
            Actions\DeleteAction::make(),
        ];
    }
}
